In [7]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, _, info = env.step(action)
    print(observation)
env.close()

[-0.00529707  0.15080631  0.03579171 -0.31812465]
[-0.00228095  0.3454007   0.02942922 -0.5993088 ]
[ 0.00462707  0.14987962  0.01744305 -0.2975032 ]
[ 0.00762466  0.34474862  0.01149298 -0.58463424]
[ 1.4519633e-02  5.3970772e-01 -1.9970271e-04 -8.7367475e-01]
[ 0.02531379  0.7348324  -0.0176732  -1.1664205 ]
[ 0.04001043  0.93017983 -0.04100161 -1.4645915 ]
[ 0.05861403  0.73558336 -0.07029343 -1.1849933 ]
[ 0.0733257   0.54144007 -0.0939933  -0.9151467 ]
[ 0.0841545   0.34770638 -0.11229623 -0.6534223 ]
[ 0.09110863  0.15431245 -0.12536468 -0.39810428]
[ 0.09419487  0.35096923 -0.13332677 -0.7275352 ]
[ 0.10121426  0.15791777 -0.14787747 -0.47961   ]
[ 0.10437261 -0.03484107 -0.15746967 -0.23694508]
[ 0.1036758  -0.22740391 -0.16220857  0.00222039]
[ 0.09912772 -0.41987282 -0.16216417  0.2396535 ]
[ 0.09073026 -0.2228506  -0.15737109 -0.09947006]
[ 0.08627325 -0.41540816 -0.1593605   0.13972065]
[ 0.07796509 -0.60793144 -0.15656608  0.37819242]
[ 0.06580646 -0.80052364 -0.14900224  

c:\Users\13306\anaconda3\envs\sb3\lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
c:\Users\13306\anaconda3\envs\sb3\lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
c:\Users\13306\anaconda3\envs\sb3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
c:\Users\13306\anaconda3\envs\sb3\lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'te

In [10]:
from gym import envs
env_specs = envs.registry
envs_ids = [env_spec for env_spec in env_specs]
print(envs_ids)

['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4']


In [4]:
import gym
env = gym.make('MountainCar-v0')
print('观测空间 = {}'.format(env.observation_space))
print('动作空间 = {}'.format(env.action_space))
print('观测范围 = {} ~ {}'.format(env.observation_space.low,
        env.observation_space.high))
print('动作数 = {}'.format(env.action_space.n))

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3
